import manifest from '../data/changelog.json';
import { TIER_LABELS } from './paths';

/**
 * Reader for the committed changelog manifest (`src/data/changelog.json`,
 * generated by `scripts/changelog/build.mjs`). Both the homepage "Latest edits"
 * feed and the `/changelog` page read through here, so there is a single source
 * of truth and zero git dependency at build time (Vercel shallow-clones).
 */

export type ChangeType =
  | 'new-article'
  | 'new-art'
  | 'art-redo'
  | 'edit'
  | 'maintenance';

export interface ChangeEvent {
  date: string; // YYYY-MM-DD (commit day, for grouping)
  iso: string; // full commit timestamp
  type: ChangeType;
  commit: string;
  // entity events
  tier?: string;
  slug?: string;
  name?: string;
  href?: string;
  art?: string; // present for new-art / art-redo
  // maintenance events
  summary?: string;
  fileCount?: number;
}

const EVENTS = manifest.events as ChangeEvent[];

export const generatedAt: string = manifest.generatedAt;

/** All events, newest-first. */
export function allEvents(): ChangeEvent[] {
  return EVENTS;
}

/** Events that belong on a reader feed — drops collapsed maintenance rows. */
export function contentEvents(): ChangeEvent[] {
  return EVENTS.filter((e) => e.type !== 'maintenance');
}

/** Human label + accent class for a change type. */
const BADGES: Record<ChangeType, { label: string; cls: string; icon?: string }> = {
  'new-article': { label: 'New article', cls: 'is-new' },
  'new-art': { label: 'New art', cls: 'is-art', icon: '🎨' },
  'art-redo': { label: 'Updated art', cls: 'is-art' },
  edit: { label: 'Edited', cls: 'is-edit' },
  maintenance: { label: 'Maintenance', cls: 'is-maint' },
};

export function badge(type: ChangeType) {
  return BADGES[type];
}

export function tierLabel(tier?: string): string {
  return tier ? (TIER_LABELS[tier] ?? tier) : '';
}

/** Group events by day (YYYY-MM-DD), preserving newest-first order. */
export function groupByDay(events: ChangeEvent[]): { date: string; events: ChangeEvent[] }[] {
  const groups: { date: string; events: ChangeEvent[] }[] = [];
  let current: { date: string; events: ChangeEvent[] } | null = null;
  for (const e of events) {
    if (!current || current.date !== e.date) {
      current = { date: e.date, events: [] };
      groups.push(current);
    }
    current.events.push(e);
  }
  return groups;
}
